{% set version = "1.4.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rnpn
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rnpn_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rnpn/rnpn_{{ version }}.tar.gz
  sha256: 1fa02ccfaa3b4344aaf9e952a6e2dcd4caac26bb50a2536ad4e54c6e45d6927b

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr
    - r-httr2 >=1.1.0
    - r-jsonlite
    - r-lifecycle
    - r-magrittr
    - r-rlang
    - r-tibble
    - r-tidyr
    - r-xml2
  run:
    - r-base
    - r-dplyr
    - r-httr2 >=1.1.0
    - r-jsonlite
    - r-lifecycle
    - r-magrittr
    - r-rlang
    - r-tibble
    - r-tidyr
    - r-xml2

test:
  commands:
    - $R -e "library('rnpn')"           # [not win]
    - "\"%R%\" -e \"library('rnpn')\""  # [win]

about:
  home: https://usa-npn.github.io/rnpn/
  dev_url: https://github.com/usa-npn/rnpn/
  license: MIT
  summary: Programmatic interface to the Web Service methods provided by the National 'Phenology' Network (<https://usanpn.org/>), which includes data on various life history events that occur at specific times.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan
